### ISSUE TITLE
How would you like the interface to look?

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#1]
Any ideas on what the plot commands should look like should go here.  See https://github.com/tbreloff/Qwt.jl for how I think it should look.

**Comment by tbreloff** [comment]
I've added a large doc section before the plot method at src/Plots.jl.  This is what I will use as a guideline for implementation (it follows pretty closely with how I made Qwt.jl)

If there are any issues with what you see, please let me know.

**Comment by jverzani** [comment]
Nice job so far! Since you asked, could you borrow the `plot(f::Function, a, b, ...)` interface from gadfly? In particular, something along the lines of:

* `plot(f::Function, a, b)` plots the function over [a,b]
* `plot([Vector{Function}, a, b)` plots the functions over [a,b] 
* `plot((f,g), a, b))` does a parametric plot over [a,b]

**Comment by tbreloff** [comment]
These should all be pretty straightforward... I'll add them next chance I get.

**Comment by tbreloff** [comment]
These are implemented now... Please take a look.

**Comment by jverzani** [comment]
Looks good. Thanks!  Whatever name this ends up with, it will be super useful. (I'm also keen on using this with 'SymPy'. I think it will help a lot. )

**Comment by tbreloff** [comment]
Is there a SymPy interface you'd like to see within Plots?  If so, open a new issue with details.

**Comment by tbreloff** [comment]
dup of #8
