### ISSUE TITLE
No support for linestyle=:none

### ISSUE THREAD

**Issue by ma-laforge** [tbreloff/Plots.jl#153]
Hi Tom,

I have noticed that Plots.jl does not support `linestyle=:none`.

The only way I know how not to display the line is to use `linetype=:scatter`.

**Comment:**
As a user, I sometimes find it preferable to set `linestyle=:none`, when possible.

I tend to associate scatter plots as a way to display unordered sets of `(x,y)` values.

I sometimes want to plot data representing sampled values of a continous, ordered dataset (like measurement data) without lines connecting the markers.  In this case, I find it a bit odd to be using the "`scatterplot`" feature.

Regards,
MA

**Comment by tbreloff** [comment]
Again, I think this should work. Might be a bug. What backend?

**Comment by tbreloff** [comment]
This works for pyplot and gadfly for me:

```julia
using Plots
plot(rand(10), lt=:none, m=(10,:h))
```

Of course, if it were me I would use `scatter`... but to each their own.

**Comment by ma-laforge** [comment]
I did not think about using the `linetype` option this way. (FYI: I was using PyPlot)

I admit, I am still a bit confused... probably because no two tools out there seem to use the same interface.  I myself am still sorting out what the different plotting terms mean (ex: Plot vs Graph), so I'm not the biggest expert at this, but...

I noticed Plots.jl defined `linetype`, which can be assigned to one of the following:
`:bar, :contour, :heatmap, :hexbin, :hist, :hline, :line, :none, :path, :scatter, :steppost, :steppre, :sticks, :vline`

I don't usually see this grouping in other plotting interfaces.  I kind like it, but I find the name confusing.  I would expect this property to be known as either "plot types", or "graph style", or something like that.

I suppose the "line graph" (`linetype=:line`) sounds like a good name for how a function of 1 variable is typically plotted...

...But I find it a bit odd to describe a graph with {symbols, but no lines} as a "none" graph.  Of course, I am aware that under your naming convention, it is a "none" linetype (not a "none" graph)...  But that makes it difficult for me to reconcile having a "heatmap" linetype.

In any case, this is just my opinion... take what you want from this... and please don't let me block your development... Thanks for the good work on Plots.jl.

**Comment by tbreloff** [comment]
>  I would expect this property to be known as either "plot types", or "graph style", or something like that.

The problem with those is that they are descriptions of the "figure" or "plot", but not of a "series".  For example, I can overlay a scatter on top of a contour map... the "plot type" is "contour with scatter", but that's kinda silly.

I agree `linetype` isn't the best term... `seriestype` is a better description.  However one of the reasons I have such extensive support for aliases is exactly this purpose.  You can call it something else.  Right now, `type`, `t`, and `lt` are all valid replacements for `linetype`.  If you really wanted to, you could add aliases yourself:

```julia
using Plots
Plots._keyAliases[:mycustomaliasforlinetype] = :linetype
plot(rand(10), mycustomaliasforlinetype = :bar)
```

I'm adding `seriestype` as an alias as we speak, and if you have any others (that don't clash with existing arguments) then let me know and I can add them.  The only downside to this is that if you want other people to be able to read your code (and intuit what it's doing), it's best to stick to conventions.

> ...But I find it a bit odd to describe a graph with {symbols, but no lines} as a "none" graph

Right... because that's a `scatter` ;)   (or `dots`, if you prefer)
