### ISSUE TITLE
IJulia display logic

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#157]
I find it annoying that IJulia seems to call multiple display formats, which is a waste and sometimes does the wrong thing.  I'll probably want to override this:

https://github.com/JuliaLang/IJulia.jl/blob/master/src/inline.jl#L31-L40

and I might want to wrap it in a `@require IJulia`.

**Comment by tbreloff** [comment]
Possible solution: https://github.com/spencerlyon2/PlotlyJS.jl/blob/5b896eb49f386fc21e8154997a24b26649df315b/src/display.jl#L102-L123

**Comment by tbreloff** [comment]
Fixed by ed1cce8

**Comment by jheinen** [comment]
Great - now it works as expected.
Will solve the GR.savestate / GR.restorestate problem (caused by exceptions) in GR -  probably by sth like GR.rewind() => to unwind the attribute stack.

**Comment by diegozea** [comment]
Hi! The IJulia notebook breaks with huge plots. Will be great to use "png" or format smaller than html/svg with very heavy plots. Thanks!

**Comment by tbreloff** [comment]
There are a couple possible options... make the display output a keyword argument during plot creation (easy-ish), or add some conditional logic to change based on data size (tricky to do well). I'm open to suggestions... Hard data and benchmarks would be important to drive implementation choices. Also this will be backend-dependent, so even trickier to get right.

**Comment by diegozea** [comment]
I prefer the keyword argument at the moment, since the conditional logic could be included in the future using a function as its default value.

**Comment by jheinen** [comment]
What about ``function backend(pkg::AbstractBackend, fmt="png")``, overwriting the ``defaultOutputFormat`` in ``output.jl``?

@diegozea :  Do you have such a _huge plot_ example? I'd like to find out what kind of output breaks IJulia (or the browser). I assume you were using the ``gr()`` backend, right?

**Comment by tbreloff** [comment]
> What about function backend(pkg::AbstractBackend, fmt="png"), overwriting the defaultOutputFormat in output.jl?

@jheinen you may not realize this, but the [convenience method](https://github.com/tbreloff/Plots.jl/blob/dev/src/backends.jl#L20) for switching backends takes optional keyword arguments that will be passed through to the `default(; kw...)` method.  This means that you can do something like:

```julia
using Plots
gr(fmt = "png")
```
and it will apply aliases and set default settings for keyword arguments.

The advantage of making it a "plot keyword" is that you can choose the format on a per-plot basis, if you want.

**Comment by diegozea** [comment]
I'm working with matrices of ~ 13000x200. I was mainly using PyPlot and PlotlyJS as backends. 

It looks as a PyPlot problem. GR and PlotlyJS show fast the huge heatmap, but the PyPlot heatmap doesn't show up with 5000 or more rows (and uses a lot of RAM trying to do it). Even a PyPlot heatmap for a matrix of 1000x200 matrix takes ~ 1m to show up, and uses 0.4G of RAM to do it.

After the plot of the 13000x200 matrix, the RAM increases 0.1G with GR and 0.3G with PlotlyJS. I remember having troubles with PlotlyJS in some IJulia sessions using a smaller computer (not only with PyPlot). PlotlyJS times are a little misleading, since `toc()` was executed by Ijulia before the plot appears.

# PyPlot
![image](https://cloud.githubusercontent.com/assets/2822757/14855357/ffbb0cbc-0c69-11e6-9edf-14f7d33d1a34.png)

# GR 
Awesome performance @jheinen !
![image](https://cloud.githubusercontent.com/assets/2822757/14855437/666749ee-0c6a-11e6-8a3a-745b8b44876b.png)
![image](https://cloud.githubusercontent.com/assets/2822757/14855831/fa50286e-0c6b-11e6-8b3d-f1a13a8f76bc.png)

# PlotlyJS

![image](https://cloud.githubusercontent.com/assets/2822757/14855723/8d87fcd4-0c6b-11e6-9990-fde7ce02b969.png)
![image](https://cloud.githubusercontent.com/assets/2822757/14855783/d1eedc8a-0c6b-11e6-8e26-9b20bef4856e.png)

# Gadfly

Gadfly doesn't support `heatmap` yet

**Comment by jheinen** [comment]
@diegozea : Thanks for the info. So, there seems to be no need to fix the problem in GR.

@tbreloff 👍 Goot to know:

```
using Plots
gr(fmt = "png")
```

**Comment by diegozea** [comment]
@tbreloff The time and memory issue with `pyplot` can be solved using `png`. Since `pyplot` is fast when the display is omitted and the plot is saved into a `png` as show it using `load`from `Images.jl` inside the IJulia notebook.
