### ISSUE TITLE
Legend not displayed using include from the REPL

### ISSUE THREAD

**Issue by maxlarsen** [tbreloff/Plots.jl#171]
Hello,

If I put this:

~~~julia
module dev

using Plots

plot(1:10,rand(10),label="hi!")

end
~~~

in a file and I `include()` it from the REPL, the graph works as expected except there is no legend. If I do `plot(1:10,rand(10),label="hi!")` from the REPL it works. Weird. The backend is the default PyPlot.

**Comment by tbreloff** [comment]
It sounds like you probably set your default value for `legend` earlier in
your session.  If you can reproduce from a fresh session then please post
the full input/output.

**Comment by maxlarsen** [comment]
This is the full session. 
![selection_024](https://cloud.githubusercontent.com/assets/16719582/13847267/b863be7a-ec22-11e5-9104-0b1123bd71f9.png)

**Comment by tbreloff** [comment]
Do you have a file '.juliarc.jl' in your home dir?

**Comment by maxlarsen** [comment]
Nope. (In case you missed it in my first post, the legend does work if I call directly `plot(1:10,rand(10),label="hi!")` from the REPL, not sure if relevant.)

**Comment by tbreloff** [comment]
Ok I'll see if I can reproduce.

**Comment by tbreloff** [comment]
Oh I think I know what's going on.  The PyPlot backend likes to create windows prematurely... it really shouldn't be displaying anything, since you never asked it to.  When you run in the REPL, it implicitly calls `display` on the Plot object.  The legend is built only when displaying the plot, which is why you see the complete plot from the REPL.  In the module, you are (incorrectly) seeing an unfinished plot.  Call display on that plot to finish it.

**Comment by maxlarsen** [comment]
I was suspecting something like that but it does not look like Plots export a `display()` or `show()`. `display()` and `Plots.display()` throw errors.

**Comment by tbreloff** [comment]
you can:

```julia
plt = plot(rand(10))
display(plt)
```

or

```julia
plot(rand(10))
gui()
```

**Comment by maxlarsen** [comment]
Yep, thanks a lot.
