### ISSUE TITLE
UnicodePlots: Points over axis

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#231]
@Evizero @tbreloff UnicodePlots and Plots using UnicodePlots don't show points over the axes
In this example, there are 164 points in `x=100` that haven't been plotted:
![image](https://cloud.githubusercontent.com/assets/2822757/15094943/d3fb10fe-1489-11e6-8f02-3555fd92e166.png)

**Comment by Evizero** [comment]
Can you try if `scatterplot`of UnicodePlots behaves similarly? Naively I would say this sounds like a Plots specific issue

**Comment by diegozea** [comment]
@Evizero I got the same with UnicodePlots' `scatterplot`

**Comment by diegozea** [comment]
i.e.: ![image](https://cloud.githubusercontent.com/assets/2822757/15096389/c910b56c-14cb-11e6-8496-0bdd4b59629f.png)

**Comment by Evizero** [comment]
ohhh, yea I know that bug actually. Well, bug, it was more of a lazy decision to say "good enough". The issue here is that if it is right at the end of the plot on the right side it is not being drawn anymore. I did at some point try to avoid it but it caused other problem. You are the first one to bring that one up actually. Mhm, maybe I do need to fix that.

**Comment by Evizero** [comment]
Come to think of it, it was pretty clear what's going on from your initial post. Don't know how I missed that. Well, it is quite early in the morning here. Yes, I will insist on that excuse :)

**Comment by Evizero** [comment]
If you want you could open this issue at unicodeplots. Otherwise I will do it later today. This one here could be closed then as I don't think Plots needs any changes in this regard

**Comment by diegozea** [comment]
I'm closing this in favor of https://github.com/Evizero/UnicodePlots.jl/issues/49 Thanks!
