### ISSUE TITLE
Is it possible that quiver() is no longer exported?

### ISSUE THREAD

**Issue by goedman** [tbreloff/Plots.jl#240]
Hi Tom, just wondering while experimenting with quiver(). Since (I think) this weekend quiver() nor Plots.quiver is exported anymore? Is that possible or am I doing something wrong?

```
using Plots
gadfly(leg=false, size=(500,300))

n = 3
x = 1:2:5
y = zeros(n)
vx, vy = randn(n), randn(n);

hcat(x, y, vx, vy)

nx = x - vx./2; ny = y - vy./2;

methods(quiver)

quiver(x, y, quiver=(vx,vy))
quiver!(nx, ny, quiver=(vx,vy))
```

**Comment by tbreloff** [comment]
I just ran the [quiver notebook](https://github.com/tbreloff/ExamplePlots.jl/blob/master/notebooks/quiver.ipynb) without issue.  Try checking out master or dev branch?

**Comment by goedman** [comment]
Switching to dev brings me back to the problem I was trying to understand:

julia> include("/Users/rob/Projects/Julia/EDx/Mathematica/Math226.2/Julia/quiver.jl")
INFO: Precompiling module Plots...
ERROR: LoadError: ArgumentError: RecipesBase not found in path
 in compilecache at loading.jl:393
 in require at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/rob/.julia/v0.4/Plots/src/Plots.jl, in expression starting on line 11
ERROR: LoadError: Failed to precompile Plots to /Users/rob/.julia/lib/v0.4/Plots.ji
 in error at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in compilecache at loading.jl:400
 in require at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/rob/Projects/Julia/EDx/Mathematica/Math226.2/Julia/quiver.jl, in expression starting on line 1

**Comment by tbreloff** [comment]
RecipesBase is a new package that (just today!) was accepted into METADATA.  It is very cool and you should look at the readme.  A `Pkg.update()` should hopefully resolve the issue.

**Comment by tbreloff** [comment]
Also I like that the file is inside a `Mathematica` directory.  :scream:

**Comment by goedman** [comment]
Hey, fall-back security... 

Indeed Master + RecipesBase fixes the problem in both Julia and the REPL!

So if I understand it correctly I should focus on RecipesBase, not so much proposing to add a 'streamplot enhanced quiver'. Very cool.

By the way, I'm (maybe optimistically) targeting a steam plot indeed more like Mathematica's:
![ex_05](https://cloud.githubusercontent.com/assets/52200/15119640/ab5d3936-15c6-11e6-9104-28fb65ddec2f.png)

We'll see how far I get.

**Comment by goedman** [comment]
Thanks for your help Tom!

**Comment by tbreloff** [comment]
FYI: I intend to support (at least) 2 different forms of recipes:

The currently implemented recipe is a converter from user data into Plots-compatible data and attributes.  This is great for DataFrames, Distributions or other custom types that are external to base julia.

Internally in Plots, I have a different type of recipe which I have been referring to as a "series recipe" (name suggestions please!! this is what makes quiver, etc).  This type of recipe accepts Plots-compatible data and attributes, then rebuilds a new series (or multiple series) to represent a visualization using component parts.

I intend to make this "series recipe" concept available as well, so that things like boxplot, quiver, etc can be moved to external packages and there's no need to have references to the recipe scattered throughout the code.  It'll be easier to define custom series types on the fly, and things like the mathematica plot you gave are just a matter of making a quiver plot with more lines/arrows.
