### ISSUE TITLE
Plots is opening the Pyplot gui in Jupyter

### ISSUE THREAD

**Issue by diegozea** [tbreloff/Plots.jl#308]
I'm in dev, using the PyPlot backend in Jupyter. The gui is open by every plot/subplot call... 

![image](https://files.gitter.im/tbreloff/Plots.jl/RXhw/blob)

**Comment by tbreloff** [comment]
I just did Pkg.update() in order to push the new Plots tag, and I picked up a new version of PyPlot:

```
INFO: Upgrading PyPlot: v2.1.1 => v2.2.0
```

Now I'm seeing this behavior as well.  I guess @stevengj 's recent fixes turned the gui back on?  @stevengj any insight as to what I need to change to get the old behavior back?  (by old behavior, I mean that the GUI isn't opened unless [this method](https://github.com/tbreloff/Plots.jl/blob/master/src/backends/pyplot.jl#L1207-L1213) is called).

**Comment by stevengj** [comment]
If I do
```jl
using PyPlot
plot(rand(10))
```
in IJulia, it doesn't open a GUI window.  Can you confirm?

If so, then it's something specific to the Plots/PyPlot interaction.

**Comment by stevengj** [comment]
Looking at [how Plots initializes PyPlot](https://github.com/tbreloff/Plots.jl/blob/7248d8d7ce901c7bf5888dfa8e7d7f44ef2e4093/src/backends/pyplot.jl#L58-L89), three things jump out:

* You don't need to call `ioff` twice
* You shouldn't call `PyPlot.pygui(true)` until/unless you actually want to turn on the GUI.
* Doing `!isa(Base.Multimedia.displays[end], Base.REPL.REPLDisplay)` seems like a pretty unreliable way to check for IJulia or a similar graphical display.

The latter line seems like the culprit to me.

**Comment by tbreloff** [comment]
I commented out the `!isa(Base.Multimedia.displays[end], Base.REPL.REPLDisplay)` block, so that the only setup is to call `PyPlot.ioff()`.  Now I'm getting the annoying behavior that an unfinished graph is displayed before the commands complete:

![tmp](https://cloud.githubusercontent.com/assets/933338/15931377/8be61e16-2e25-11e6-8c4a-3cd191afd0ca.png)

Any ideas?

**Comment by tbreloff** [comment]
Also when I try to open a gui window I get:

```
/home/tom/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/figure.py:397: UserWarning: matplotlib is currently using a non-GUI backend, so cannot show the figure
  "matplotlib is currently using a non-GUI backend, "
```

even though `PyPlot.gui == :qt_pyqt4`.

**Comment by tbreloff** [comment]
Thanks for any help @stevengj... I was always really confused by the display mechanics of PyPlot.jl... hopefully any solution won't be as hacky as before.

**Comment by stevengj** [comment]
When you want to open a gui window, you need pygui(true) ... even if it is using the qt backend, it calls switch_backend in IJulia to switch to the Agg backend

**Comment by stevengj** [comment]
Regarding the double display, I should probably add a mechanism to avoid redisplaying the figure (which occurs after cell execution... the purpose is to make the plot display as a side effect, without requiring an explicit display call nor requiring the plot to be the cell return value) if display is called on it. There was some logic like that before, but it got eliminated by the new way I handle plotting in IJulia.

**Comment by tbreloff** [comment]
For the gui display, I changed to:

```julia
function _display(plt::Plot{PyPlotBackend})
    PyPlot.pygui(true)
    plt.o[:show]()
    PyPlot.pygui(false)
end
```

but I still see the same error:

```
/home/tom/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/figure.py:397: UserWarning: matplotlib is currently using a non-GUI backend, so cannot show the figure
  "matplotlib is currently using a non-GUI backend, "
```

**Comment by tbreloff** [comment]
@stevengj regarding the double-display in IJulia... do you know where in PyPlot that first display happens?  Maybe I can hack it somehow to turn it off only in Plots.  Fixing this is pretty high on my priority list right now.

**Comment by tbreloff** [comment]
And just fyi... the `pygui(true)` call is unnecessary in the REPL (just a `show` is enough), and it doesn't seem to have any affect in IJulia.

**Comment by tbreloff** [comment]
I figured out a double-display solution:

```
# we don't want every command to update the figure
PyPlot.ioff()

# this will stop PyPlot.jl from forcing display of all figures (which double-displays)
PyPlot.isjulia_display[1] = false
```

I presume the reason is that it won't enter [this method](https://github.com/stevengj/PyPlot.jl/blob/master/src/PyPlot.jl#L321-L332).  However I'm a little worried that new figures will be created and never closed because of all the monkey-patching-type-stuff.  @stevengj you obviously know more about this topic than me... let me know if you think this is a solution that is good enough.  Thanks!

**Comment by tbreloff** [comment]
I might have found an even nicer solution, if you're willing to accept a tiny PR.  In Plots:

```
--- a/src/backends/pyplot.jl
+++ b/src/backends/pyplot.jl
@@ -57,6 +57,7 @@ subplotSupported(::PyPlotBackend) = true
 
 function _initialize_backend(::PyPlotBackend)
     @eval begin
+        ENV["OVERRIDE_PYPLOT_DISPLAY"] = true
         import PyPlot
         export PyPlot
```

in PyPlot:

```
--- a/src/PyPlot.jl
+++ b/src/PyPlot.jl
@@ -208,7 +208,7 @@ end
 # initialization -- anything that depends on Python has to go here,
 # so that it occurs at runtime (while the rest of PyPlot can be precompiled).
 function __init__()
-    global const isjulia_display = Bool[isdisplayok()]
+    global const isjulia_display = Bool[!haskey(ENV, "OVERRIDE_PYPLOT_DISPLAY") && isdisplayok()]
     copy!(matplotlib, pyimport_conda("matplotlib", "matplotlib"))
     global const version = try
         convert(VersionNumber, matplotlib[:__version__])
```

This solution fixes both the gui issue and the double display!  I'll submit a PR... hopefully it's acceptable.

**Comment by tbreloff** [comment]
This will be fixed when https://github.com/stevengj/PyPlot.jl/pull/223 is merged.  cc: @stevengj
