### ISSUE TITLE
Plots not working in Atom

### ISSUE THREAD

**Issue by dlfivefifty** [tbreloff/Plots.jl#348]
I get the following error:

```julia
MethodError: `_writemime` has no method matching _writemime(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::MIME{symbol("text/plain")}, ::Plots.Plot{Plots.GRBackend})
Closest candidates are:
  _writemime(::IO, ::MIME{symbol("text/plain")}, !Matched::Plots.Plot{Plots.UnicodePlotsBackend})
  _writemime(::IO, !Matched::MIME{symbol("application/postscript")}, ::Plots.Plot{Plots.GRBackend})
  _writemime(::IO, !Matched::MIME{symbol("application/pdf")}, ::Plots.Plot{Plots.GRBackend})
  ...
```

**Comment by dlfivefifty** [comment]
Using pyplot I get the same error:

```julia
MethodError: `_writemime` has no method matching _writemime(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::MIME{symbol("text/plain")}, ::Plots.Plot{Plots.PyPlotBackend})
Closest candidates are:
  _writemime(::IO, !Matched::MIME{symbol("image/eps")}, ::Plots.Plot{Plots.PyPlotBackend})
  _writemime(::IO, !Matched::MIME{symbol("application/eps")}, ::Plots.Plot{Plots.PyPlotBackend})
  _writemime(::IO, !Matched::MIME{symbol("application/postscript")}, ::Plots.Plot{Plots.PyPlotBackend})
  ...
```

**Comment by ChrisRackauckas** [comment]
That used to show up much less, but now it seems to be more common. It's annoying, but Plots still works even when that error is thrown.

**Comment by tbreloff** [comment]
Sorry guys I can't test. But I saw Mile's lightning talk at JuliaCon and Im
going to give Atom/Juno another try sometime soon. Until then I'll accept
PRs that fix Atom issues!

**Comment by dlfivefifty** [comment]
Looking forward to this being fixed!  It seems that Atom is about the only useable IDE at the moment (LT/Juno is way too buggy), but not having Plots is a serious issue…especially since there was a good solid week where Plots and Atom worked great together.  I guess I’m back to Jupyter...

**Comment by dlfivefifty** [comment]
Actually, at the moment it doesn't look like any plotting is working in Atom...even with PyPlot.jl or GR.jl

**Comment by cstook** [comment]
I see the same problem with pyplot(), plotly(), and plotlyjs() backends.

**Comment by mkborregaard** [comment]
Seconded. Having Plots working in Atom would solve my IDE woes.

**Comment by samuelpowell** [comment]
Is there a known workaround for this problem?

**Comment by ChrisRackauckas** [comment]
By default it works. It just doesn't plot in the plot pane.

**Comment by samuelpowell** [comment]
@ChrisRackauckas, my experience (on OS X) seems to differ.

When I issue
```
using Plots; pyplot(); plot(rand(100))
``` 
a blank icon opens in the dock (as it would if I were plotting directly with PyPlot), but no output is displayed. A warning is also printed: `WARNING: _writemime is not defined for this backend. m=text/plain`.

**Comment by ChrisRackauckas** [comment]
Did you not use `gui()`?

**Comment by samuelpowell** [comment]
I had not, this works now. Thank you for your help.

So that I understand clearly, am I correct in thinking that `Atom.jl` or a related package is setting an environment variable (which would not be set at the REPL) to plot inline, but that this is not yet fully supported?

**Comment by ChrisRackauckas** [comment]
No. Here's the full story.

This issue with using `gui()` is due to how the REPL displays. By default, the REPL displays the object that's given. However, once you go into script evaluation mode, it turns off default printing (that's why you don't need to use semicolons in a script). Atom's evaluation uses the script evaluation, so it doesn't print by default. It simulates the default printing via Media.jl, but doesn't have anything for plots. So you have to call `display(p)` on your plot, or just use the handy `gui()` that Plots.jl provides for that.

The Atom plot pane is turned off by a global variable defined in Plots.jl because there are some bugs in the current implementation. You can flip it on/off anytime (search for the issue on it), but just to warn you, unless Tom has updated it you'll have some issues. In the meantime, you can always plot with plots getting their own windows by just using `gui()`.

`WARNING: _writemime is not defined for this backend. m=text/plain` is just a warning that Atom throws. I don't know why, but it seems harmless, at least if you're not using the plot pane (but may be way the plot pane doesn't work?).

**Comment by samuelpowell** [comment]
@ChrisRackauckas thank you for the explanation!

**Comment by ChrisRackauckas** [comment]
This is all related to #437

**Comment by tbreloff** [comment]
Closing in favor of #437
