### ISSUE TITLE
Feature Request: spy() function

### ISSUE THREAD

**Issue by joshday** [tbreloff/Plots.jl#40]
Hi Tom.  Matlab has a `spy()` function for viewing the sparsity pattern of a matrix.  I like the way Gadfly implements `spy()`, which is to make a heatmap from a matrix (https://github.com/JuliaLang/julia/issues/2121).  I didn't see a way to do this through the Plots.jl api.

**Comment by tbreloff** [comment]
I wrapped the call to heatmap. Available on master for Gadfly, Immerse, PyPlot, Qwt:

<img width="656" alt="screen shot 2015-10-04 at 9 40 22 pm" src="https://cloud.githubusercontent.com/assets/933338/10272135/b45a756c-6ae0-11e5-9a9d-09c0226d48a3.png">

**Comment by ptoche** [comment]
Any ideas? Thanks.

    workspace()
    SM = eye(5)
    SM[end, end] = -1
    using Gadfly
    spy(SM)

    WARNING: both Gadfly and Base export "cross"; uses of it in module Main must be qualified

Also tried the following, but no plot was produced.

    p = spy(SM)
    display(p)

Julia + Plots updated as of a few minutes ago.

**Comment by mkborregaard** [comment]
Hi @ptoche - if you find an issue, it is better to open a new issue than comment on an old closed one, especially if the problem is different. We don't keep track of closed issues, so problems will not be solved. If you just have a question, the gitter channel is a good place to find us.

It does indeed look like the spy recipe is broken, and you should probably open a new issue, preferably with a screenshot detailing your problem.

However, your code would never work. You're calling Gadfly, but gadfly is no longer  a Plots backend, and also you cannot call a Plots backend with `using`. For Plots, the code would look like this:
```julia
using Plots; gr()
SM = eye(5)
SM[end, end] = -1
spy(SM)
```

**Comment by mkborregaard** [comment]
`spy` isn't implemented as a heatmap anymore, BTW. You can just do a heatmap if that's what you'd like.

**Comment by ptoche** [comment]
@mkborregaard, thanks for your reply. I wasn't sure it was an 'issue' as such or my misunderstanding of the plotting syntax. Apparently both.  

I had some Matlab code that used the ``spy()`` function, so I googled for ``Julia+spy`` and got here pretty quickly, which is why I left a message here. Other trails took me to [](https://stackoverflow.com/questions/33732330/using-spy-in-julia), but that didn't help much.

**Comment by alanedelman** [comment]
so what's the good way to get spy with squares and not invisible dots?
(and matrix coordinates please?)

**Comment by joshday** [comment]
Try something like `spy(x, marker = (:square, 5))` or `heatmap(x, yflip = true)`

**Comment by mkborregaard** [comment]
Yes the markers are set very small by default in spy, so as not to overlap with the functionality of heatmap
