### ISSUE TITLE
linestyle=:stem conflicts with yscale=:log10

### ISSUE THREAD

**Issue by baggepinnen** [tbreloff/Plots.jl#435]
On Plots
```
julia> plot(abs(randn(10)),yscale=:log10, l=:stem)
Error showing value of type Plots.Plot{Plots.PyPlotBackend}:
ERROR: At least one finite value must be provided to formatter.
```

problem occurs for both PyPlot and GR so I guess it's independent of backend.

```
julia> versioninfo()
Julia Version 0.5.0-rc0+99
Commit c10667f* (2016-08-01 07:45 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblasp.so.0
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by tbreloff** [comment]
I can reproduce.  Looking into it

**Comment by tbreloff** [comment]
So here's what's happening... the `:sticks` recipe converts points into a bunch of line segments, in this case from 0 to y.  `log10(0) == -Inf`, so the tick calculation breaks and returns `-Inf`, and the default formatter from Showoff.jl isn't happy with that.  You can override the formatter so there's no error, but the resulting plot looks pretty weird.  You can also explicitly set `fillrange = 1e-3` so that it doesn't try to fill to 0.

I can't think of a good solution here, except maybe giving a warning in the sticks recipe that you need to explicitly set `fillrange` with a log scale?

**Comment by baggepinnen** [comment]
I kind of guessed that was the issue..

Some ideas, no solution:
I guess one would like to have the stems always start at the bottom of the
plot, but this information might not be available at the time the sticks
are drawn?
Another option is to have the sticks drawn from the lowest value of the set
of data points? This would however look strange if more than one series was
plotted in the same plot.

**Comment by tbreloff** [comment]
Both of these suggestions would give similar results, where the line would fill to the lowest data point, though filling to the bottom of the plot area is probably more robust.  I suppose they're both better than erroring!
