### ISSUE TITLE
Export to png saves white image (plotly backend)

### ISSUE THREAD

**Issue by AntonioLoureiro** [tbreloff/Plots.jl#441]
When using plotly() backend, the command png(filename) saves a white image.

Julia v0.4.6
Plots v0.8.2
Plotly v0.1.0
```
using Plots
plotly()

plot(rand(10))

png("test.png")
```

**Comment by mmagnuski** [comment]
what if you do:
```julia
p = plot(rand(10))
png(p, "test.png")
```

**Comment by tbreloff** [comment]
It is known... (GoT anyone?)

PNG generation is tricky for Plotly because it has to run and render javascript and then build a static image from a dynamic javascript page.  You should give plotlyjs a try because @spencerlyon2 has spent much more time solving this specific problem (and there are lots of other super cool features)
