### ISSUE TITLE
Supporting Gadfly as a backend

### ISSUE THREAD

**Issue by ViralBShah** [tbreloff/Plots.jl#518]
Now that Gadfly is well supported again, thanks to @tlnagy, is it possible to re-enable it as a supported Plots.jl backend?

Cc @shashi

**Comment by tbreloff** [comment]
Is this a request? Or a heads up that you'll be working on it?

See https://github.com/tbreloff/Plots.jl/issues/261#issuecomment-221292047
for a little background.

My current feeling is that it's a waste of my time to do anything with
Gadfly. There's just no reason. If you feel strongly about putting your own
time into it then fine, but I'd prefer people put their efforts into other
backends.

**Comment by ViralBShah** [comment]
Thanks for the pointer. Maybe we should close this for now, and I will do some further digging. The main reason I like Gadfly is to have a pure Julia based plotting, but as you suggest, perhaps Compose.jl may be the way to get there.

**Comment by SimonDanisch** [comment]
Well, GLVisualize almost supports the whole range of Plots.jl by now...

**Comment by tlnagy** [comment]
I think Gadfly and Plots have different aims and can co-exist. One of the primary benefits of Gadfly is its grammar of graphics interface and the consistency of its output. This would be lost if it was used as only a backend with little gain. 

@SimonDanisch GLVisualize is awesome and it might be fun to extend Compose to leverage it. The performance gains should be huge.

**Comment by SimonDanisch** [comment]
What exactly do you mean by extending Compose? ;)
I implemented a GLVisualize for Gadfly once... I guess it's currently not functional, though ;)

**Comment by tlnagy** [comment]
We can move this discussion elsewhere (either to Compose/Gadfly or to GLVisualize) so to not spam everyone else here. I meant using GLVisualize as a backend for Compose in addition to (and maybe eventually instead of) Cairo/Pango.

**Comment by ChrisRackauckas** [comment]
Maybe this should be re-opened as Supporting Gadfly/Compose. Now that there is a framework for how a GoG API can exist within Plots.jl, and there are PlotThemes so that Plots.jl can looks like Gadfly, I think there is a good discussion to be had with @tlnagy about what Gadfly gives that the new API over Plots into Compose does not, or whether there are parts of Gadfly that can be used to build the Plots over Compose.

**Comment by SimonDanisch** [comment]
Btw, what I've written _was_ a backend for Compose replacing Cairo ;) It hasn't been that beneficial, because it turned out that the major performance problems don't always lay within Cairo, and the major advantages of GLVisualize (fast animations and 3D) just disappear. Bringing them to Gadfly would mean a major overhaul, which didn't seem beneficial at that time. I'm open to reevaluation, though :) But Plots.jl would need a much smaller overhaul to deliver all benefits of GLVisualize.

**Comment by tlnagy** [comment]
I suspect that the a lot of the performance problems in Gadfly stem from the same reasons as DataFrames'. There's just a lot of cruft and legacy hacks that don't make sense any more that Base has improved so much. I agree with @SimonDanisch that it's going to be a non-trivial exercise to bring Gadfly up to speed and I don't think any of the current maintainers have that kind of time.
