### ISSUE TITLE
Move image files out of repo

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#54]
Right now I have several sources of large, non-critical files, all with their full change history, bloating the repo:
- Example images
- Example notebooks
- Test images

I want to come up with a solution to keep these separate from the code, since they are not required in order to import Plots, and I want the repo to be as lightweight as possible.

Some ideas I've considered:
- Github's large-file-storage
  - Seems clean, easy to use
  - Not sure how I feel about the infrastructure dependency... will it also require internet at all times?
- Separate repos (TestPlots.jl, ExamplePlots.jl, StatPlots.jl, etc)
  - Keeps each minimal
  - Extra bookkeeping
  - Might want to put all these in the JuliaPlot org?  Though maybe StatPlots.jl would belong in JuliaStats
- Hosted solution
  - Serve static files, move docs to html site

I'm open to suggestion... any other ideas?

Also when this is done I'll want to purge the commit history of the old binary files.  See: http://stackoverflow.com/questions/6358476/how-to-remove-old-versions-of-media-files-from-a-git-repository

**Comment by tbreloff** [comment]
See: https://github.com/tbreloff/ExamplePlots.jl

**Comment by lewisl** [comment]
Just put them in another git repo and link to it.  Then you can document them a bit.

Turns out it is a very bad problem to have them at all.  If you run the examples locally, you have modified files in the git working set and you make the package dirty, which makes it impossible to manage with Pkg.  I spent 20' just cleaning up several <>_example_<>.gif files.  Super annoying.

**Comment by lewisl** [comment]
The auto-dirty feature has been purged in 0.4.2.

**Comment by tbreloff** [comment]
I think all image-type assets live in ExamplePlots.jl now, so closing.
