### ISSUE TITLE
Gray image can not be displayed as an true image

### ISSUE THREAD

**Issue by Gnimuc** [tbreloff/Plots.jl#588]
Take a look at the following toy example:
```julia
using Plots, Images; #gr()
plot(grayim(rand(16,16)))
```
![grayim](https://cloud.githubusercontent.com/assets/7437173/20626164/e0e9fd12-b352-11e6-9c7d-ab32151253fc.png)

It seems that Plots considered the gray image as a common matrix. However, other image types can be displayed correctly. I guess this might due to the data structure of the gray image which is indeed a plain Matrix.

**Comment by tbreloff** [comment]
Hmm this is tricky.  The type from grayim is a subset of AbstractArray{Float64,2}... not the same as if you loaded it from a file.  In order to define a recipe that would work, I'd have to add a dependency on Images (which I don't want).  Another option would be to add the recipe to Images itself, which would require a dependency on RecipesBase (cc @timholy)

The current workaround is to explicitly map this to a matrix of colors:

```julia
using Plots, Images
img = convert(Matrix{Gray}, grayim(rand(16,16)))
plot(img)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/20672826/9734f226-b550-11e6-8500-93f01b7b8ecf.png)

**Comment by timholy** [comment]
In the "new Images" (see https://github.com/timholy/Images.jl/issues/542, especially https://github.com/timholy/Images.jl/issues/542#issuecomment-254059092) it will return something of type `Gray`, so your intention will be clear.

**Comment by tbreloff** [comment]
@timholy do you mean that with the new Images the `convert` will be unnecessary? (I.e. The `grayim` call will return a "matrix of Gray"?) If so, that's great... nothing to be done.

**Comment by timholy** [comment]
But yes, nothing you need to do here.

**Comment by tbreloff** [comment]
Cool... gonna close this then.  Thanks!
