### ISSUE TITLE
Position plots side by side

### ISSUE THREAD

**Issue by Evizero** [tbreloff/Plots.jl#75]
Basically I would like to create two seperate plots and then unify them. In R I would do

```R
p1 <- qplot(x, y, data=set1)
p2 <- qplot(z, data=somethingDifferent)

grid.arrange(p1, p1, ncol=2)
```

Is there something similar I can do with Plots.jl? I can't quite figure out how the subplot is supposed to work. For example it seems like I can't do different xlabels for two subplots.

**Comment by Evizero** [comment]
I found out I can do the following

```Julia
vstack(p1.o, p2.o)
```

But I don't think this works with your animation stuff, which is the reason why I actually want to do it in the first place. Any ideas?

**Comment by Evizero** [comment]
allright, digging in the code I found out how subplots work and that i can write

```Julia
subplot(p1, p2)
```

sorry for wasting your time.

**Comment by tbreloff** [comment]
Heh... you're too quick for me.  I started to prepare a response and you solved it too quickly.  Just to add, in case someone else stumbles on this.  You can have linked or unlinked subplots, like this:

```
with(grid=false, size=(400,200), leg=false) do
    subplot(plot(rand(10)), plot(5*rand(10)), link=true)
end
```
![tmp](https://cloud.githubusercontent.com/assets/933338/11302031/dbb4e866-8f68-11e5-86a2-d3eb4454b897.png)

Which makes rows share x-axes, and columns share y-axes.  You can also set `linkx`/`linky` to link only the rows/columns.

ps - I uncovered a bug in the pyplot backend when creating subplots from existing plots... so this issue was not in vain!

**Comment by Evizero** [comment]
love it! see attached a little intro example I produced with Plots.jl
btw: any idea how I can change the size of the plot in the notebook?

![line](https://cloud.githubusercontent.com/assets/10854026/11302390/76830b14-8f9d-11e5-9167-12338d44d122.gif)

**Comment by tbreloff** [comment]
This is cool!  As for changing the size, any of these should work:

```
default(size=(500,500))
subplot(...)
```

```
with(size=(500,500)) do
  subplot(...)
end
```

```
subplot(..., size=(500,500))
```

The difference is just the scoping.  Calling default will change the size for all plotting commands in the session going forward.  The `with` method changes it just for the `do` block.  If you use the subplot argument then it's just for that one command.
