### ISSUE TITLE
Add support for GR.jl backend support?

### ISSUE THREAD

**Issue by AzamatB** [tbreloff/Plots.jl#94]
It would be good to have a support for GR.jl backend (https://github.com/jheinen/GR.jl), given it's speed

**Comment by tbreloff** [comment]
I don't have any experience with GR. How does it compare to pyplot/matplotlib in features/speed? Ignoring interface (since Plots is your new universal interface), is there a compelling reason that GR is worth the effort?  Does GR.jl go through python/PyCall?

If you want to create the first PR for basic support, please do. If it's compelling we can expand support.

**Comment by AzamatB** [comment]
Here is the talk on it from JuliaCon 2015: https://www.youtube.com/watch?v=RVnYRk_6wvE&list=PLP8iPy9hna6Sdx4soiGrSefrmOPdUWixM&index=18

Haven't used it personally, but they claim to be faster than pyplot/matplotlib with comparable list of features and maturity. Being fully written in C, (according to developers) it can handle well large datasets (with > 10^6 records).

**Comment by tbreloff** [comment]
I missed that talk at JuliaCon. Sounds compelling. If someone could give some bare minimal usage examples I could throw together a prototype. I'm concurrently working on the Plotly and GLVisualize backends (as well as trying to beat DeepMind at their AGI game ;) so no promises on when I get to this.

**Comment by AzamatB** [comment]
For your reference, examples + documentation: http://gr-framework.org/index.html

**Comment by tbreloff** [comment]
Cc @jheinen

This library seems very low level. I don't reasonably see myself pushing this forward alone, as it will take a while to learn the framework. If anyone wants to take this on, Let me know.

**Comment by jheinen** [comment]
With the next release it should be easier to add support for GR.jl in Plots.jl, as we will add (MATLAB-like) convenience functions. Unfortunately, this version will not be available before January 2016.

**Comment by tbreloff** [comment]
Josef: in that case, let me make the case for skipping that step, and spending your time on quality Plots.jl integration.  Creating a good user api is an orthogonal goal to having quality/fast plotting capabilities. If you create the link code within Plots, then you get the extensive user api for free (as well as any future improvements).  I'm happy to talk you through how to do this, but I don't want to do it alone. I'm happy to skype sometime if you want to discuss further.

**Comment by lobingera** [comment]
@jheinen 
Do you plan the convenience functions to be implemented in julia or in C?

**Comment by jheinen** [comment]
Time-critical functions will be / are already implemented in C. We plan to provide the same functionality both in Julia and Python. But to achieve "convenience", some parts have to be implemented in Julia or Python due to different language concepts.

**Comment by AzamatB** [comment]
@jheinen what do you think about @tbreloff 's proposition?

**Comment by jheinen** [comment]
Sound great, but I will first have to take a closer look to the Plots.jl link code. If it turns out, that this approach is applicable to the GR framework, I will pursue that idea in any case.

**Comment by tbreloff** [comment]
@jheinen check out https://github.com/tbreloff/Plots.jl/blob/master/src/backends/template.jl, and other implementations in the backends directory, which gives you a rough idea of what you can do within link code.

From the high level, you can implement setup/creation of plot pieces at several parts of the pipeline... plot creation, adding series, displaying, etc.  For clean backends, you may only need to implement a few of these methods.  The easiest way to get started will be for us to work together.  I did this with @spencerlyon2 to get initial support for Bokeh in only a couple hours (although we've both moved on to Plotly since then, and never finished full support of Bokeh)

**Comment by jheinen** [comment]
The fact that I published a new GR.jl release today should not create the impression that I'm implementing my own solution, regardless of Plots.jl. Our users push for a convenient API for the 3D functions (GR3), e.g. the representation of molecules and 2D primitives in one canvas - something I have promised to be available in January 2016, both in Julia and Python. As soon as we have finished this API, we will focus on getting support for Plots.jl - I'm really aware, that an abstraction layer for the existing Julia plot packages is very important and we will try to find a solution (based on the backend template) ASAP.

**Comment by jheinen** [comment]
@tbreloff FYI: I started writing a GR backend for Plots.jl: https://github.com/jheinen/Plots.jl

**Comment by tbreloff** [comment]
Cool!  Let me know if you have any questions.

**Comment by jheinen** [comment]
@tbreloff: implemented line/scatter plots using GR - will move parts of the code into GR's C libraries. First PR probably in January ...

**Comment by tbreloff** [comment]
Please move TODO/roadmap discussion to #108
