### ISSUE TITLE
surface! with plot() causes KeyError

### ISSUE THREAD

**Issue by dlfivefifty** [tbreloff/Plots.jl#95]
```julia
using Plots
x,y=1:0.1:10,1:0.05:10
z=Float64[exp(x)*cos(y) for x in x, y in y]
p=plot()
surface!(x,y,z)
```
gives error
```julia
ERROR: KeyError: plot_surface not found
 in getindex at /Users/solver/.julia/v0.4/PyCall/src/PyCall.jl:239
 in getindex at /Users/solver/.julia/v0.4/PyCall/src/PyCall.jl:244
 in getPyPlotFunction at /Users/solver/.julia/v0.4/Plots/src/backends/pyplot.jl:146
 in _add_series at /Users/solver/.julia/v0.4/Plots/src/backends/pyplot.jl:255
 in plot! at /Users/solver/.julia/v0.4/Plots/src/plot.jl:119
 in plot! at /Users/solver/.julia/v0.4/Plots/src/plot.jl:69
 in surface! at /Users/solver/.julia/v0.4/Plots/src/Plots.jl:170
```

**Comment by tbreloff** [comment]
This is expected, and I'm not sure what the correct solution should be.  `plot_surface` is a function of matplotlib's 3d library.  You are creating a 2D matplotlib axis, and then trying to call a 3D method.  Because matplotlib has separate libraries for 2D and 3D, I don't know if you can easily mix and match the two.  Here's the method that needs to be called... see that it's part of an `Axes3D` object: http://matplotlib.org/mpl_toolkits/mplot3d/tutorial.html#surface-plots

I'll note that this example seems to work fine with the Plotly backend, so it's likely a PyPlot-only issue.

**Comment by dlfivefifty** [comment]
OK, that’s fair enough, but then this should work:

```julia
p=surface();
x,y=0:.1:1.,0:.1:1.
z=exp(x)*cos(y)'
surface!(x,y,z)
```

**Comment by tbreloff** [comment]
I suppose so, although I don't know why you'd need to do that.  Anyways I'll try to fix.

**Comment by dlfivefifty** [comment]
The reason I would use this is so that I only have to override one routine, i.e., my pattern would be:

function surface!(p::Plot,f::Fun)
	# do stuff to create x, y, z
	surface!(p,x,y,z)
end
surface!(f::Fun)=surface!(current(),f)
surface(f::Fun)=surface!(surface(),f)

**Comment by tbreloff** [comment]
I'm not positive, but it sounds like you should be implementing _apply_recipe... See the source and issues in tbreloff/MLPlots.jl for examples of what I mean.

**Comment by tbreloff** [comment]
This issue should be fixed in dev... please check it out.
